baseurl: https://devcows.github.io/hugo-universal-theme/
title: DataSciLabs
theme: hugo-universal-theme
languageCode: en-us
defaultContentLanguage: pt-br
disqusShortname: devcows
googleAnalytics: ''
summaryLength: 70
paginate: 10
pluralizelisttitles: no
menu:
  main:
    - identifier: menu.home
      name: Página Inicial
      url: /
      weight: 1
    - identifier: menu.blog
      name: Blog
      url: /blog/
      weight: 2
    - identifier: menu.faq
      name: Sobre
      url: /faq/
      weight: 3
    - identifier: contact
      name: Contato
      url: /contact/
      weight: 4
    - identifier: equipe
      name: Equipe
      url: /equipe/
      weight: 5
  topbar:
    - name: Phone
      pre: <i class='fas fa-2x fa-phone'></i>
      url: tel:+12 34 567 89 01
      weight: 1
    - name: GitHub
      pre: <i class='fab fa-2x fa-github'></i>
      url: https://github.com/devcows/hugo-universal-theme
      weight: 2
    - name: Facebook
      pre: <i class='fab fa-2x fa-facebook'></i>
      url: http://facebook.com
      weight: 3
    - name: Twitter
      pre: <i class='fab fa-2x fa-twitter'></i>
      url: http://twitter.com
      weight: 4
    - name: Email
      pre: <i class='fas fa-2x fa-envelope'></i>
      url: mailto:hello@universal.com
      weight: 5
params:
  about_us: <p>Somos um Programa de Extensão em Ciência de Dados da UFPR</p>
  address: "<p class=\"text-uppercase\"><strong>DataSciLabs</strong>\n        <bUFPR\n        <br>Jardim das Américas\n        <br>Curitiba\n
    \       <br>\n        <strong>Brasil</strong>\n      </p>\n      "
  author: DevCows
  carouselCustomers:
    auto_play: no
    items: 5
    pagination_speed: 1000
    slide_speed: 2000
  carouselHomepage:
    auto_play: yes
    enable: yes
    pagination_speed: 1000
    slide_speed: 2000
  carouselTestimonials:
    auto_play: no
    items: 4
    pagination_speed: 1000
    slide_speed: 2000
  clients:
    enable: yes
    subtitle: ''
    title: Colaboradores
  contact_form_ajax: no
  contact_url: /contact
  copyright: Copyright (c) 2023, DataSci Labs UFPR. All rights reserved.
  date_format: January 2, 2006
  default_sharing_image: img/sharing-default.png
  defaultDescription: Site template made by Devcows using Hugo
  defaultKeywords:
    - devcows
    - hugo
    - go
  disabled_logo: no
  dropdown_mouse_over: no
  enableGoogleMaps: yes
  enableRecaptchaInContactForm: no
  facebook_site: ''
  features:
    cols: 3
    enable: yes
  social_media:
    cols: 2
    enable: yes
  footer:
    recent_posts:
      enable: yes
  formspree_action: https://formspree.io/sample/of/endpoint
  googleMapsApiKey: AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY
  googleRecaptchaKey: site_key_for_google_recaptcha
  latitude: '-12.043333'
  logo: img/logo-dsl.jpeg
  logo_small: img/logo-small.png
  logo_text: DataSciLabs
  longitude: '-77.028333'
  mainSections: blog
  recent_posts:
    enable: yes
    hide_summary: no
    subtitle: Nossos posts recentes
    title: Posts
  see_more:
    enable: no
    icon: far fa-file-alt
    link_text: Check other homepages
    link_url: '#'
    subtitle: We have prepared for you more than 40 different HTML pages, including
      5 variations of homepage.
    title: Do you want to see more?
  style: violet
  testimonials:
    enable: yes
    subtitle: Depoimentos dos professores do Departamento de Estatística da Universidade
     Federal do Paraná sobre o projeto extensionista e suas expectativas em relação a ele.
  #subtitle: We have worked with many clients and we always like to hear they come
     #out from the cooperation happy and satisfied. Have a look what our clients said
     #about us.
    title: Depoimentos
  #title: Testimonials
  topbar:
    enable: no
    text: "<p class=\"hidden-sm hidden-xs\">Contact us on +420 777 555 333 or hello@universal.com.</p>\n
      \     <p class=\"hidden-md hidden-lg\"><a href=\"tel:+420 777 555 333\" data-animate-hover=\"pulse\"><i
      class=\"fas fa-phone\"></i></a>\n      <a href=\"mailto:hello@universal.com\"
      data-animate-hover=\"pulse\"><i class=\"fas fa-envelope\"></i></a>\n      </p>\n
      \     "
  twitter_site: GoHugoIO
  viewMorePostLink: /blog/
  widgets:
    categories: yes
    search: yes
    tags: yes
permalinks:
  blog: /blog/:year/:month/:day/:filename/
taxonomies:
  author: authors
  category: categories
  tag: tags
